#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import re
import json

# Đọc file HTML
with open('e:\\profineCV\\Web_learn_Chinese_pro\\public\\user\\radicals-214.html', 'r', encoding='utf-8') as f:
    content = f.read()

# Bảng mnemonic cho mỗi bộ thủ
mnemonics = {
    1: "\"Một\" - Nét duy nhất, từ một mà ra tất cả các chữ Hán. Gốc rễ của mọi sự.",
    2: "\"Nét sổ\" - Một nét thẳng đứng, giống như chiếc que gỗ đứng thẳng trên đất.",
    3: "\"Dấu chấm\" - Một dấu chấm nhỏ, như hạt nước rơi từ lá cây.",
    4: "\"Nét phẩy\" - Nét xiên từ trên xuống, như đường rơi của tuyết.",
    5: "\"Thiên can 2\" - Hình dáng uốn cong, như con đường quanh co.",
    6: "\"Nét sổ có móc\" - Nét thẳng với móc, giống chiếc câu câu cá.",
    7: "\"Số hai\" - Hai nét ngang, biểu thị sự nhân đôi.",
    8: "\"Đầu/Nét trên\" - Cái mũ trên đầu, bảo vệ tất cả những gì ở dưới.",
    9: "\"Người\" - Hai cánh tay xõa xuống, hình dáng đặc trưng của con người.",
    10: "\"Người hình chân\" - Chân của con người, giúp ta đi bộ khắp thế gian.",
    11: "\"Vào\" - Hình dáng của chiếc cửa mở rộng, thách thức bạn vào bên trong.",
    12: "\"Số tám\" - Hai nhánh cây mở rộng, tượng trưng sự phân chia.",
    13: "\"Vùng xa\" - Hộp kín bốn phía, bao quanh một khu vực bí mật.",
    14: "\"Khăn trùm\" - Chiếc khăn che phủ, giấu diều bên dưới.",
    15: "\"Nước đá\" - Nước đông lạnh, sáng loáng như băng trên sông.",
    16: "\"Bàn nhỏ\" - Một cái bàn nhỏ, nơi sắp xếp những vật dụng.",
    17: "\"Há miệng\" - Miệng há mở, như khi giật mình hoặc ngạc nhiên.",
    18: "\"Con dao\" - Lưỡi dao sắc bén, cắt và gọt mọi thứ.",
    19: "\"Sức mạnh\" - Cơ bắp dồn sức, biểu thị sức mạnh.",
    20: "\"Bao bọc\" - Vòng tay quấn lấy, bảo vệ những gì bên trong.",
    21: "\"Cái thìa\" - Cái thìa nhỏ, dùng để múc và nêm thức ăn.",
    22: "\"Hộp\" - Hộp vuông kín, chứa đựng những thứ quý giá.",
    23: "\"Che đậy\" - Che phủ bằng vải, ẩn chứa bí mật.",
    24: "\"Số mười\" - Dấu cộng, nơi gặp nhau của hai đường.",
    25: "\"Xem bói\" - Dùng để xem bói, tiên đoán tương lai.",
    26: "\"Đốt tre\" - Một đốt tre, nơi dâng tế lễ.",
    27: "\"Vách núi\" - Vách núi thẳng đứng, tạo thành hang động.",
    28: "\"Riêng tư\" - Một góc nhỏ riêng tư, chỉ có một mình.",
    29: "\"Lại nữa\" - Một bàn tay, ngón tay gợi ý thêm lần nữa.",
    30: "\"Miệng\" - Một hình vuông, lỗ mở để ăn uống.",
    31: "\"Bao quanh\" - Hộp kín, bao quanh hoàn toàn.",
    32: "\"Đất\" - Đất bề mặt, nơi trồng trọt xây dựng.",
    33: "\"Kẻ sĩ\" - Con người cao quý, nhân vật ưu tú.",
    34: "\"Đi chậm\" - Chân đi chậm, như người già.",
    35: "\"Đi chậm\" - Tương tự chân đi, nhưng khác cách.",
    36: "\"Buổi tối\" - Mặt trời lặn, bóng tối buông xuống.",
    37: "\"To lớn\" - Con người xõa tay, sự rộng lớn.",
    38: "\"Phụ nữ\" - Người phụ nữ quỳ, tượng trưng nữ giới.",
    39: "\"Con cái\" - Em bé nhỏ, tượng trưng con cái.",
    40: "\"Mái nhà\" - Mái nhà che chở, tạo căn nhà.",
    41: "\"Đơn vị đo\" - Khoảng cách ngắn, đơn vị cơ bản.",
    42: "\"Nhỏ bé\" - Một hạt nhỏ, biểu thị điều bé xíu.",
    43: "\"Yếu\" - Người yếu ớt, mọi chuyện khó khăn.",
    44: "\"Xác chết\" - Xác chết nằm, biểu thị chết chóc.",
    45: "\"Mầm non\" - Mầm cây mọc lên, hy vọng sống mới.",
    46: "\"Núi\" - Ba đỉnh núi xếp chồng lên nhau.",
    47: "\"Sông\" - Dòng sông chảy, giữa hai bờ.",
    48: "\"Công việc\" - Khung công trình, biểu thị lao động.",
    49: "\"Bản thân\" - Bản thân tôi, sự tự nhận thức.",
    50: "\"Khăn\" - Chiếc khăn vuông, dùng để lau.",
    51: "\"Can thiên\" - Cái gậy hoặc thanh ngang.",
    52: "\"Nhỏ\" - Rất nhỏ bé, như hạt bụi gió.",
    53: "\"Mái nhà\" - Mái nhà rộng, che phủ tất cả.",
    54: "\"Bước dài\" - Bước dài sang một bên, tiến tới.",
    55: "\"Chắp tay\" - Hai tay ghép lại, cảm ơn.",
    56: "\"Bắn\" - Mũi tên bắn ra, tấn công mục.",
    57: "\"Cái cung\" - Cái cung bắn tên, sức mạnh.",
    58: "\"Đầu nhím\" - Đầu nhím với gai, phòng thủ.",
    59: "\"Lông tóc\" - Ba sợi tóc, tượng trưng.",
    60: "\"Bước chân\" - Bước chân sang bên, đi bộ.",
    61: "\"Tim\" - Tim đập, trái tim cảm xúc.",
    62: "\"Binh khí\" - Chiến giáo, vũ khí cổ đại.",
    63: "\"Cửa\" - Cửa căn nhà, cơ sở cuộc sống.",
    64: "\"Tay\" - Tay với năm ngón, công cụ lao động.",
    65: "\"Cành\" - Cành cây nhánh, phân tách.",
    66: "\"Đánh nhẹ\" - Đánh nhẹ bằng gậy, kiểm soát.",
    67: "\"Văn chương\" - Những nét chữ viết, văn hoá.",
    68: "\"Cái đấu\" - Cái đo lường, giả tạ.",
    69: "\"Rìu\" - Cái rìu cắt gỗ, công cụ.",
    70: "\"Vuông\" - Hình vuông hoàn hảo.",
    71: "\"Không\" - Không có gì, sự trống rỗng.",
    72: "\"Mặt trời\" - Mặt trời sáng rực, nguồn sáng.",
    73: "\"Nói\" - Miệng mở nói, giao tiếp.",
    74: "\"Mặt trăng\" - Mặt trăng tròn, ánh sáng đêm.",
    75: "\"Cây\" - Cây cối mọc, sự sống xanh.",
    76: "\"Thiếu\" - Miệng há, biểu thị thiếu.",
    77: "\"Dừng\" - Chân dừng lại, ngừng bước.",
    78: "\"Xấu\" - Xác chết, biểu thị xấu xa.",
    79: "\"Binh khí\" - Chiếc gậy, vũ khí cơ bản.",
    80: "\"Chớ\" - Không được phép, cấm chỉ.",
    81: "\"So sánh\" - Hai người đứng cạnh.",
    82: "\"Lông\" - Sợi lông, biểu thị mềm.",
    83: "\"Họ\" - Họ của người, danh tính.",
    84: "\"Hơi\" - Hơi thở, năng lượng sống.",
    85: "\"Nước\" - Nước chảy, sự dịu dàng.",
    86: "\"Lửa\" - Lửa bùng cháy, nhiệt độ cao.",
    87: "\"Móng vuốt\" - Móng vuốt sắc bén.",
    88: "\"Cha\" - Cha của gia đình, bảo vệ.",
    89: "\"Âm dương\" - Đương kết hợp, hòa quyện.",
    90: "\"Mảnh gỗ\" - Mảnh gỗ bẻ ra.",
    91: "\"Miếng\" - Miếng đứt, nửa cái gì.",
    92: "\"Răng\" - Hàng răng cười, giao tiếp.",
    93: "\"Trâu\" - Con trâu mạnh, lao động.",
    94: "\"Chó\" - Con chó trung thành, bảo vệ.",
    95: "\"Đen huyền\" - Màu đen huyền bí.",
    96: "\"Đá quý\" - Ngọc quý cổ, giá trị cao.",
    97: "\"Dưa\" - Trái dưa tròn, cái gì ngon.",
    98: "\"Ngói\" - Ngói mái nhà, che phủ.",
    99: "\"Ngọt\" - Ngọt lịm, hương vị dễ chịu.",
    100: "\"Sống\" - Sự sống mới, tự do.",
    101: "\"Dùng\" - Dùng để làm gì, có ích.",
    102: "\"Ruộng\" - Ruộng lúa mênh mông.",
    103: "\"Tấm\" - Tấm vải, đơn vị đo.",
    104: "\"Bệnh\" - Bệnh tật, khổ đau.",
    105: "\"Gạt\" - Gạt ngược, lật lọng.",
    106: "\"Trắng\" - Màu trắng sạch, sáng.",
    107: "\"Da\" - Da người, vỏ ngoài.",
    108: "\"Bát đĩa\" - Bát ăn, vật dụng nhà bếp.",
    109: "\"Mắt\" - Mắt nhìn, cửa sổ tâm hồn.",
    110: "\"Giáo\" - Chiến giáo dài, tấn công.",
    111: "\"Mũi tên\" - Mũi tên bay, chuẩn xác.",
    112: "\"Đá\" - Đá cứng, chắc chắn.",
    113: "\"Chỉ thị\" - Chỉ thị của thần linh.",
    114: "\"Dấu vết\" - Dấu vết trên đất.",
    115: "\"Lúa\" - Lúa vàng, sự sung túc.",
    116: "\"Hang\" - Hang động, chỗ ẩn trú.",
    117: "\"Đứng\" - Đứng thẳng, thành lập.",
    118: "\"Tre\" - Tre thẳng mềm dẻo.",
    119: "\"Gạo\" - Hạt gạo, lương thực.",
    120: "\"Sợi tơ\" - Sợi tơ tớ, kết nối.",
    121: "\"Đồ sành\" - Cái chum sành, chứa nước.",
    122: "\"Lưới\" - Cái lưới câu cá, bắt.",
    123: "\"Dê\" - Con dê, tính tình hiền.",
    124: "\"Lông vũ\" - Lông vũ bay, nhẹ.",
    125: "\"Già\" - Người già, sự yếu.",
    126: "\"Và\" - Cái tóc dài, liên kết.",
    127: "\"Cái cày\" - Cái cày, canh tác.",
    128: "\"Tai\" - Tai nghe, lắng nghe.",
    129: "\"Bút\" - Cây bút viết, sáng tạo.",
    130: "\"Thịt\" - Thịt người, cơ thể.",
    131: "\"Bề tôi\" - Bề tôi quỳ, tôn kính.",
    132: "\"Bản thân\" - Bản thân tôi, tự giác.",
    133: "\"Đến\" - Đến đích, hoàn thành.",
    134: "\"Cối gạo\" - Cối giã gạo, chế biến.",
    135: "\"Lưỡi\" - Lưỡi nói, giao tiếp.",
    136: "\"Sai\" - Sai lệch, trái chiều.",
    137: "\"Thuyền\" - Thuyền trên sông, khám phá.",
    138: "\"Dừng\" - Dừng lại, cứng rắn.",
    139: "\"Màu\" - Màu sắc đa dạng.",
    140: "\"Cỏ\" - Cỏ xanh, tự nhiên.",
    141: "\"Vằn hổ\" - Hổ hung dữ, sức mạnh.",
    142: "\"Sâu\" - Sâu bọ, sinh vật nhỏ.",
    143: "\"Máu\" - Máu chảy, sự sống.",
    144: "\"Đi\" - Đi bộ, hành động.",
    145: "\"Áo\" - Áo quần, che thân.",
    146: "\"Che\" - Che phủ phía tây.",
    147: "\"Thấy\" - Mắt nhìn, hiểu biết.",
    148: "\"Sừng\" - Sừng con động vật.",
    149: "\"Nói\" - Miệng nói lời, giao tiếp.",
    150: "\"Khe núi\" - Khe núi sâu, tiếng vang.",
    151: "\"Hạt\" - Hạt đậu, dinh dưỡng.",
    152: "\"Heo\" - Con heo, tính khí.",
    153: "\"Thú\" - Thú hoang, bản năng.",
    154: "\"Vỏ sò\" - Vỏ sò cổ, tiền tệ.",
    155: "\"Đỏ\" - Màu đỏ rực, cháy bỏng.",
    156: "\"Chạy\" - Chạy nhanh, trốn chạy.",
    157: "\"Chân\" - Chân bước, hành động.",
    158: "\"Cơ thể\" - Cơ thể con người.",
    159: "\"Xe\" - Xe chạy, giao thông.",
    160: "\"Cay\" - Cay khổ, khó nhọc.",
    161: "\"Địa chi\" - Thời gian sáng tỏ.",
    162: "\"Đi\" - Đi xa, di chuyển.",
    163: "\"Vùng\" - Vùng đất, thành phố nhỏ.",
    164: "\"Rượu\" - Rượu ngon, lễ hội.",
    165: "\"Phân biệt\" - Phân biệt sáng tối.",
    166: "\"Làng\" - Làng quê, khoảng cách.",
    167: "\"Kim loại\" - Kim loại quý, giá.",
    168: "\"Dài\" - Dài sâu, lâu dài.",
    169: "\"Cửa\" - Cửa hai cánh, ra vào.",
    170: "\"Gò đất\" - Gò đất cao, địa hình.",
    171: "\"Kịp\" - Theo kịp, dần dần.",
    172: "\"Chim\" - Chim bay, nhẹ nhàng.",
    173: "\"Mưa\" - Mưa tuôn, sự tươi mát.",
    174: "\"Xanh\" - Xanh lam, màu sắc.",
    175: "\"Không\" - Không phải, phủ định.",
    176: "\"Mặt\" - Mặt người, bề mặt.",
    177: "\"Da\" - Da thú, thay đổi.",
    178: "\"Da thuộc\" - Da đã xử lý.",
    179: "\"Rau hẹ\" - Rau hẹ mùi, ăn.",
    180: "\"Âm thanh\" - Âm thanh vang.",
    181: "\"Đầu\" - Đầu người, trang sách.",
    182: "\"Gió\" - Gió thổi, sự bay bổng.",
    183: "\"Bay\" - Bay cao, tự do.",
    184: "\"Ăn\" - Ăn cơm, dinh dưỡng.",
    185: "\"Đầu\" - Đầu tiên, lãnh đạo.",
    186: "\"Mùi\" - Mùi thơm, quyến rũ.",
    187: "\"Ngựa\" - Con ngựa, tốc độ.",
    188: "\"Xương\" - Xương chắc, cơ bản.",
    189: "\"Cao\" - Cao vút, tầm nhìn rộng.",
    190: "\"Tóc\" - Tóc dài, nhan sắc.",
    191: "\"Chiến\" - Chiến đấu, cạnh tranh.",
    192: "\"Rượu nếp\" - Rượu lễ, tôn kính.",
    193: "\"Đỉnh\" - Cái đỉnh cổ, nấu.",
    194: "\"Quỷ\" - Con quỷ, bí ẩn.",
    195: "\"Cá\" - Con cá, sự bơi lội.",
    196: "\"Chim\" - Con chim, bay lượn.",
    197: "\"Đất mặn\" - Đất mặn, khô cằn.",
    198: "\"Hươu\" - Con hươu, tài lộc.",
    199: "\"Lúa mạch\" - Lúa mạch vàng.",
    200: "\"Gai\" - Cây gai, sợi vải.",
    201: "\"Vàng\" - Vàng rực, giá trị.",
    202: "\"Lúa nếp\" - Lúa nếp, bánh.",
    203: "\"Đen\" - Đen kịt, tối tăm.",
    204: "\"May vá\" - May vá áo, công phu.",
    205: "\"Ếch\" - Ếch eo ơi, nhảy nhót.",
    206: "\"Cái đỉnh\" - Cái đỉnh ba chân.",
    207: "\"Trống\" - Cái trống, phô trương.",
    208: "\"Chuột\" - Con chuột, tinh tế.",
    209: "\"Mũi\" - Cái mũi sắc, ngửi.",
    210: "\"Ngang\" - Ngang bằng, cân xứng.",
    211: "\"Răng\" - Hàng răng, cắn nhai.",
    212: "\"Rồng\" - Con rồng huyền bí.",
    213: "\"Rùa\" - Con rùa lâu đời.",
    214: "\"Ống sáo\" - Ống sáo, tiếng gọi."
}

print("Generated mnemonics for", len(mnemonics), "radicals")
