#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate mnemonics for 214 Chinese radicals
"""

mnemonics = {
    1: "一 (Nhất - Số một): Một nét duy nhất, từ một mà ra tất cả. Đó là gốc rễ của mọi chữ Hán.",
    2: "丨 (Cổn - Nét sổ): Một nét thẳng đứng, giống như chiếc que gỗ đứng thẳng trên đất.",
    3: "丶 (Chủ - Dấu chấm): Một dấu chấm nhỏ, như hạt nước rơi từ lá cây.",
    4: "丿 (Phiệt - Nét phẩy): Nét xiên từ trên xuống, như đường rơi của tuyết.",
    5: "乙 (Ất - Thiên can 2): Hình dáng uốn cong, như con đường quanh co.",
    6: "亅 (Quyết - Nét sổ có móc): Nét thẳng với móc, giống chiếc câu câu cá.",
    7: "二 (Nhị - Số hai): Hai nét ngang, biểu thị sự nhân đôi, từ một thành hai.",
    8: "亠 (Đầu - Đầu/Nét trên): Cái mũ trên đầu, bảo vệ tất cả những gì ở dưới.",
    9: "人 (Nhân - Người): Hai cánh tay xõa xuống, hình dáng đặc trưng của con người.",
    10: "儿 (Nhi - Người hình chân): Chân của con người, giúp ta đi bộ khắp thế gian.",
    11: "入 (Nhập - Vào): Hình dáng của chiếc cửa mở rộng, thách thức bạn vào bên trong.",
    12: "八 (Bát - Số tám): Hai nhánh cây mở rộng, tượng trưng sự phân chia.",
    13: "冂 (Quynh - Vùng xa): Hộp kín bốn phía, bao quanh một khu vực bí mật.",
    14: "冖 (Mịch - Khăn trùm): Chiếc khăn che phủ, giấu diều bên dưới.",
    15: "冫 (Băng - Nước đá): Nước đông lạnh, sáng loáng như băng trên sông.",
    16: "几 (Kỷ - Bàn nhỏ): Một cái bàn nhỏ, nơi sắp xếp những vật dụng.",
    17: "凵 (Khảm - Há miệng): Miệng há mở, như khi giật mình hoặc ngạc nhiên.",
    18: "刀 (Đao - Con dao): Lưỡi dao sắc bén, cắt và gọt mọi thứ.",
    19: "力 (Lực - Sức mạnh): Cơ bắp dồn sức, biểu thị sức mạnh và năng lực.",
    20: "勹 (Bao - Bao bọc): Vòng tay quấn lấy, bảo vệ những gì bên trong.",
    21: "匕 (Chủy - Cái thìa): Cái thìa nhỏ, dùng để múc và nêm thức ăn.",
    22: "匚 (Phương - Hộp): Hộp vuông kín, chứa đựng những thứ quý giá.",
    23: "匸 (Hệ - Che đậy): Che phủ bằng vải, ẩn chứa bí mật bên trong.",
    24: "十 (Thập - Số mười): Dấu cộng, nơi gặp nhau của hai đường thẳng.",
    25: "卜 (Bốc - Xem bói): Dùng để xem bói, tiên đoán tương lai.",
    26: "卩 (Tiết - Đốt tre): Một đốt tre, nơi dâng tế lễ cho thần thánh.",
    27: "厂 (Hán - Vách núi): Vách núi thẳng đứng, tạo thành các hang động.",
    28: "厶 (Tư - Riêng tư): Một góc nhỏ riêng tư, chỉ có một mình.",
    29: "又 (Hựu - Lại nữa): Một bàn tay, ngón tay gợi ý 'thêm một lần nữa'.",
    30: "口 (Khẩu - Miệng): Một hình vuông, lỗ mở để ăn uống nói chuyện.",
    31: "囗 (Vi - Bao quanh): Hộp kín, bao quanh hoàn toàn, không có lối thoát.",
    32: "土 (Thổ - Đất): Đất bề mặt, nơi ta trồng trọt và xây dựng nhà cửa.",
    33: "士 (Sĩ - Kẻ sĩ): Con người cao quý, nhân vật ưu tú trong xã hội.",
    34: "夂 (Trĩ - Đi chậm): Chân đi chậm, như người già bước từng bước.",
    35: "夊 (Tuy - Đi chậm): Tương tự chân đi, nhưng khác cách viết.",
    36: "夕 (Tịch - Buổi tối): Mặt trời lặn, bóng tối buông xuống.",
    37: "大 (Đại - To lớn): Con người xõa tay, thể hiện sự rộng lớn.",
    38: "女 (Nữ - Phụ nữ): Người phụ nữ quỳ gối, tượng trưng nữ giới.",
    39: "子 (Tử - Con cái): Em bé nhỏ, tượng trưng con cái và tuổi trẻ.",
    40: "宀 (Miên - Mái nhà): Mái nhà che chở, tạo nên căn nhà ấm cúng.",
    41: "寸 (Thốn - Đơn vị đo): Một khoảng cách ngắn, đơn vị cơ bản đo đạc.",
    42: "小 (Tiểu - Nhỏ bé): Một hạt nhỏ, biểu thị điều gì đó bé xíu.",
    43: "尢 (Uông - Yếu): Người yếu ớt, mọi chuyện khó khăn với họ.",
    44: "尸 (Thi - Xác chết): Xác chết nằm, biểu thị sự chết chóc.",
    45: "屮 (Triệt - Mầm non): Mầm cây mọc lên, hy vọng sự sống mới.",
    46: "山 (Sơn - Núi): Ba đỉnh núi xếp chồng lên nhau.",
    47: "川 (Xuyên - Sông): Dòng sông chảy, giữa hai bờ.",
    48: "工 (Công - Công việc): Khung công trình, biểu thị lao động xây dựng.",
    49: "己 (Kỷ - Bản thân): Bản thân tôi, sự tự nhận thức.",
    50: "巾 (Cân - Khăn): Chiếc khăn vuông, dùng để lau và che phủ.",
    51: "干 (Can - Can thiên): Cái gậy hoặc thanh ngang, bảo vệ.",
    52: "幺 (Yêu - Nhỏ): Rất nhỏ bé, như hạt bụi trong gió.",
    53: "广 (Nghiễm - Mái nhà): Mái nhà rộng, che phủ tất cả bên dưới.",
    54: "廴 (Dẫn - Bước dài): Bước dài sang một bên, tiến tới.",
    55: "廾 (Củng - Chắp tay): Hai tay ghép lại, cảm ơn hoặc cầu nguyện.",
    56: "弋 (Dặc - Bắn): Mũi tên bắn ra, tấn công mục tiêu.",
    57: "弓 (Cung - Cái cung): Cái cung bắn tên, sức mạnh của chiến binh.",
    58: "彐 (Kệ - Đầu nhím): Đầu nhím với gai nhọn, phòng thủ.",
    59: "彡 (Sam - Lông tóc): Ba sợi tóc, tượng trưng sự xinh đẹp.",
    60: "彳 (Xích - Bước chân): Bước chân sang bên trái, sự đi bộ.",
    61: "心 (Tâm - Tim): Tim đập, trái tim của cảm xúc.",
    62: "戈 (Qua - Binh khí): Chiến giáo, vũ khí của lính cổ đại.",
    63: "户 (Hộ - Cửa): Cửa căn nhà, cơ sở của cuộc sống.",
    64: "手 (Thủ - Tay): Tay với năm ngón, công cụ lao động.",
    65: "支 (Chi - Cành): Cành cây nhánh, phân tách.",
    66: "攴 (Phộc - Đánh nhẹ): Đánh nhẹ bằng gậy, kiểm soát.",
    67: "文 (Văn - Văn chương): Những nét chữ viết, biểu thị văn hoá.",
    68: "斗 (Đẩu - Cái đấu): Cái đo lường, giả tạ nước.",
    69: "斤 (Cân - Rìu): Cái rìu cắt gỗ, công cụ hữu ích.",
    70: "方 (Phương - Vuông): Hình vuông hoàn hảo, biểu thị sự cân bằng.",
    71: "无 (Vô - Không): Không có gì, sự trống rỗng.",
    72: "日 (Nhật - Mặt trời): Mặt trời sáng rực, nguồn sáng.",
    73: "曰 (Viết - Nói): Miệng mở nói, giao tiếp.",
    74: "月 (Nguyệt - Mặt trăng): Mặt trăng tròn, ánh sáng đêm.",
    75: "木 (Mộc - Cây): Cây cối mọc, sự sống xanh.",
    76: "欠 (Khiếm - Thiếu): Miệng há, biểu thị thiếu hụt.",
    77: "止 (Chỉ - Dừng): Chân dừng lại, ngừng bước.",
    78: "歹 (Đãi - Xấu): Xác chết, biểu thị sự xấu xa.",
    79: "殳 (Thù - Binh khí): Chiếc gậy, vũ khí cơ bản.",
    80: "毋 (Vô - Chớ): Không được phép, cấm chỉ.",
    81: "比 (Tỷ - So sánh): Hai người đứng cạnh, so sánh.",
    82: "毛 (Mao - Lông): Sợi lông, biểu thị mềm mượt.",
    83: "氏 (Thị - Họ): Họ của người, danh tính.",
    84: "气 (Khí - Hơi): Hơi thở, năng lượng sống.",
    85: "水 (Thủy - Nước): Nước chảy, biểu thị sự dịu dàng.",
    86: "火 (Hỏa - Lửa): Lửa bùng cháy, nhiệt độ cao.",
    87: "爪 (Trảo - Móng vuốt): Móng vuốt sắc bén, tấn công.",
    88: "父 (Phụ - Cha): Cha của gia đình, bảo vệ.",
    89: "爻 (Hào - Âm dương): Đương kết hợp, âm dương hòa quyện.",
    90: "爿 (Tường - Mảnh gỗ): Mảnh gỗ bẻ ra, phân chia.",
    91: "片 (Phiến - Miếng): Miếng đứt, nửa của cái gì đó.",
    92: "牙 (Nha - Răng): Hàng răng cười, truyền thông.",
    93: "牛 (Ngưu - Trâu): Con trâu mạnh, lao động.",
    94: "犬 (Khuyển - Chó): Con chó trung thành, bảo vệ.",
    95: "玄 (Huyền - Đen huyền): Màu đen huyền bí, lạ kỳ.",
    96: "玉 (Ngọc - Đá quý): Ngọc quý cổ, giá trị cao.",
    97: "瓜 (Qua - Dưa): Trái dưa tròn, cái gì ngon lành.",
    98: "瓦 (Ngõa - Ngói): Ngói mái nhà, che phủ.",
    99: "甘 (Cam - Ngọt): Ngọt lịm, hương vị dễ chịu.",
    100: "生 (Sinh - Sống): Sự sống mới, tự do.",
    101: "用 (Dụng - Dùng): Dùng để làm gì, có ích.",
    102: "田 (Điền - Ruộng): Ruộng lúa mênh mông, đất canh tác.",
    103: "疋 (Thất - Tấm): Tấm vải, đơn vị đo.",
    104: "疒 (Nạch - Bệnh): Bệnh tật, khổ đau.",
    105: "癶 (Bát - Gạt): Gạt ngược, lật lọng.",
    106: "白 (Bạch - Trắng): Màu trắng sạch, sáng.",
    107: "皮 (Bì - Da): Da người, vỏ ngoài.",
    108: "皿 (Mãnh - Bát đĩa): Bát ăn, vật dụng nhà bếp.",
    109: "目 (Mục - Mắt): Mắt nhìn, cửa sổ tâm hồn.",
    110: "矛 (Mâu - Giáo): Chiến giáo dài, tấn công.",
    111: "矢 (Thỉ - Mũi tên): Mũi tên bay, chuẩn xác.",
    112: "石 (Thạch - Đá): Đá cứng, chắc chắn.",
    113: "示 (Thị - Chỉ thị): Chỉ thị của thần linh, điều thiêng.",
    114: "禸 (Nhựu - Dấu vết): Dấu vết trên đất, theo dõi.",
    115: "禾 (Hòa - Lúa): Lúa vàng, sự sung túc.",
    116: "穴 (Huyệt - Hang): Hang động, chỗ ẩn trú.",
    117: "立 (Lập - Đứng): Đứng thẳng, thành lập.",
    118: "竹 (Trúc - Tre): Tre thẳng mềm dẻo, thần bí.",
    119: "米 (MỄ - Gạo): Hạt gạo, lương thực.",
    120: "糸 (Mịch - Sợi tơ): Sợi tơ tớ, kết nối.",
    121: "缶 (Phẫu - Đồ sành): Cái chum sành, chứa nước.",
    122: "网 (Võng - Lưới): Cái lưới câu cá, bắt giữ.",
    123: "羊 (Dương - Dê): Con dê, tính tình hiền lành.",
    124: "羽 (Vũ - Lông vũ): Lông vũ bay, sự nhẹ nhàng.",
    125: "老 (Lão - Già): Người già, sự yếu đuối.",
    126: "而 (Nhi - Và): Cái tóc dài, liên kết.",
    127: "耒 (Lôi - Cái cày): Cái cày, chuyên canh tác.",
    128: "耳 (Nhĩ - Tai): Tai nghe, lắng nghe.",
    129: "聿 (Duật - Bút): Cây bút viết, sáng tạo.",
    130: "肉 (Nhục - Thịt): Thịt người, cơ thể.",
    131: "臣 (Thần - Bề tôi): Bề tôi quỳ, sự tôn kính.",
    132: "自 (Tự - Bản thân): Bản thân tôi, sự tự giác.",
    133: "至 (Chí - Đến): Đến đích, hoàn thành.",
    134: "臼 (Cửu - Cối gạo): Cối giã gạo, nơi chế biến.",
    135: "舌 (Thiệt - Lưỡi): Lưỡi nói, giao tiếp.",
    136: "舛 (Suyễn - Sai): Sai lệch, trái chiều.",
    137: "舟 (Chu - Thuyền): Thuyền trên sông, khám phá.",
    138: "艮 (Cấn - Dừng): Dừng lại, cứng rắn.",
    139: "色 (Sắc - Màu): Màu sắc đa dạng, cung cấp.",
    140: "艸 (Thảo - Cỏ): Cỏ xanh, tự nhiên.",
    141: "虍 (Hô - Vằn hổ): Hổ hung dữ, sức mạnh.",
    142: "虫 (Trùng - Sâu): Sâu bọ, sinh vật nhỏ.",
    143: "血 (Huyết - Máu): Máu chảy, sự sống.",
    144: "行 (Hành - Đi): Đi bộ, hành động.",
    145: "衣 (Y - Áo): Áo quần, che thân.",
    146: "襾 (Á - Che): Che phủ phía tây.",
    147: "見 (Kiến - Thấy): Mắt nhìn, hiểu biết.",
    148: "角 (Giác - Sừng): Sừng con động vật, bảo vệ.",
    149: "言 (Ngôn - Nói): Miệng nói lời, giao tiếp.",
    150: "谷 (Cốc - Khe núi): Khe núi sâu, tiếng vang.",
    151: "豆 (Đậu - Hạt): Hạt đậu, dinh dưỡng.",
    152: "豕 (Thỉ - Heo): Con heo, tính khí.",
    153: "豸 (Trĩ - Thú): Thú hoang, bản năng.",
    154: "貝 (Bối - Vỏ sò): Vỏ sò cổ, tiền tệ.",
    155: "赤 (Xích - Đỏ): Màu đỏ rực, cháy bỏng.",
    156: "走 (Tẩu - Chạy): Chạy nhanh, trốn chạy.",
    157: "足 (Túc - Chân): Chân bước, hành động.",
    158: "身 (Thân - Cơ thể): Cơ thể con người, sự hiện diện.",
    159: "車 (Xa - Xe): Xe chạy, giao thông.",
    160: "辛 (Tân - Cay): Cay khổ, khó nhọc.",
    161: "辰 (Thìn - Địa chi): Thời gian sáng tỏ, ngày mới.",
    162: "辵 (Sước - Đi): Đi xa, di chuyển.",
    163: "邑 (Ấp - Vùng): Vùng đất, thành phố nhỏ.",
    164: "酉 (Dậu - Rượu): Rượu ngon, lễ hội.",
    165: "釆 (Biện - Phân biệt): Phân biệt sáng tối, quyết định.",
    166: "里 (Lý - Làng): Làng quê, khoảng cách.",
    167: "金 (Kim - Kim loại): Kim loại quý, giá trị.",
    168: "長 (Trường - Dài): Dài sâu, lâu dài.",
    169: "門 (Môn - Cửa): Cửa hai cánh, ra vào.",
    170: "阜 (Phụ - Gò đất): Gò đất cao, địa hình.",
    171: "隶 (Đãi - Kịp): Theo kịp, dần dần.",
    172: "隹 (Truy - Chim): Chim bay, nhẹ nhàng.",
    173: "雨 (Vũ - Mưa): Mưa tuôn, sự tươi mát.",
    174: "青 (Thanh - Xanh): Xanh lam, màu sắc.",
    175: "非 (Phi - Không): Không phải, phủ định.",
    176: "面 (Diện - Mặt): Mặt người, bề mặt.",
    177: "革 (Cách - Da): Da thú, thay đổi.",
    178: "韋 (Vi - Da thuộc): Da đã xử lý, mềm.",
    179: "韭 (Phỉ/Cựu - Rau hẹ): Rau hẹ mùi, ăn gỡi.",
    180: "音 (Âm - Âm thanh): Âm thanh vang, giao tiếp.",
    181: "頁 (Hiệt - Đầu): Đầu người, trang sách.",
    182: "風 (Phong - Gió): Gió thổi, sự bay bổng.",
    183: "飛 (Phi - Bay): Bay cao, tự do.",
    184: "食 (Thực - Ăn): Ăn cơm, dinh dưỡng.",
    185: "首 (Thủ - Đầu): Đầu tiên, lãnh đạo.",
    186: "香 (Hương - Mùi): Mùi thơm, quyến rũ.",
    187: "馬 (Mã - Ngựa): Con ngựa, tốc độ.",
    188: "骨 (Cốt - Xương): Xương chắc, cơ bản.",
    189: "高 (Cao - Cao): Cao vút, tầm nhìn rộng.",
    190: "髟 (Bưu - Tóc): Tóc dài, nhan sắc.",
    191: "鬥 (Đấu - Chiến): Chiến đấu, cạnh tranh.",
    192: "鬯 (Sưởng - Rượu nếp): Rượu lễ, tôn kính.",
    193: "鬲 (Cách - Đỉnh): Cái đỉnh cổ, nấu nướng.",
    194: "鬼 (Quỷ - Quỷ): Con quỷ, bí ẩn.",
    195: "魚 (Ngư - Cá): Con cá, sự bơi lội.",
    196: "鳥 (Điểu - Chim): Con chim, bay lượn.",
    197: "鹵 (LỖ - Đất mặn): Đất mặn, khô cằn.",
    198: "鹿 (Lộc - Hươu): Con hươu, tài lộc.",
    199: "麥 (Mạch - Lúa mạch): Lúa mạch vàng, mùa gặt.",
    200: "麻 (Ma - Gai): Cây gai, sợi vải.",
    201: "黃 (Hoàng - Vàng): Vàng rực, giá trị.",
    202: "黍 (Thụ - Lúa nếp): Lúa nếp, dùng làm bánh.",
    203: "黑 (Hắc - Đen): Đen kịt, tối tăm.",
    204: "黹 (Chỉ - May vá): May vá áo, công phu.",
    205: "黽 (Mãnh - Ếch): Ếch eo ơi, nhảy nhót.",
    206: "鼎 (Đỉnh - Cái đỉnh): Cái đỉnh ba chân, quyền lực.",
    207: "鼓 (Cổ - Trống): Cái trống, phô trương.",
    208: "鼠 (Thụ - Chuột): Con chuột, tinh tế.",
    209: "鼻 (Tỳ - Mũi): Cái mũi sắc, ngửi mùi.",
    210: "齊 (Tề - Ngang): Ngang bằng, cân xứng.",
    211: "齒 (Xỉ - Răng): Hàng răng, cắn nhai.",
    212: "龍 (Long - Rồng): Con rồng huyền bí, quyền lực.",
    213: "龜 (Quy - Rùa): Con rùa lâu đời, khôn ngoan.",
    214: "龠 (Dược - Ống sáo): Ống sáo, tiếng gọi thiên nhiên."
}

# Create Python code to generate the updated data
output = []
for num, mnemonic in mnemonics.items():
    output.append(f"        {num}: '{mnemonic}',")

print("Mnemonics dictionary created with {} entries".format(len(mnemonics)))
