#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import re

# Bảng mnemonic cho mỗi bộ thủ
mnemonics = {
    1: "Một nét duy nhất, từ một mà ra tất cả các chữ Hán. Gốc rễ của mọi sự.",
    2: "Một nét thẳng đứng, giống như chiếc que gỗ đứng thẳng trên đất.",
    3: "Một dấu chấm nhỏ, như hạt nước rơi từ lá cây.",
    4: "Nét xiên từ trên xuống, như đường rơi của tuyết.",
    5: "Hình dáng uốn cong, như con đường quanh co.",
    6: "Nét thẳng với móc, giống chiếc câu câu cá.",
    7: "Hai nét ngang, biểu thị sự nhân đôi.",
    8: "Cái mũ trên đầu, bảo vệ tất cả những gì ở dưới.",
    9: "Hai cánh tay xõa xuống, hình dáng đặc trưng của con người.",
    10: "Chân của con người, giúp ta đi bộ khắp thế gian.",
    11: "Hình dáng của chiếc cửa mở rộng, thách thức bạn vào bên trong.",
    12: "Hai nhánh cây mở rộng, tượng trưng sự phân chia.",
    13: "Hộp kín bốn phía, bao quanh một khu vực bí mật.",
    14: "Chiếc khăn che phủ, giấu diều bên dưới.",
    15: "Nước đông lạnh, sáng loáng như băng trên sông.",
    16: "Một cái bàn nhỏ, nơi sắp xếp những vật dụng.",
    17: "Miệng há mở, như khi giật mình hoặc ngạc nhiên.",
    18: "Lưỡi dao sắc bén, cắt và gọt mọi thứ.",
    19: "Cơ bắp dồn sức, biểu thị sức mạnh.",
    20: "Vòng tay quấn lấy, bảo vệ những gì bên trong.",
    21: "Cái thìa nhỏ, dùng để múc và nêm thức ăn.",
    22: "Hộp vuông kín, chứa đựng những thứ quý giá.",
    23: "Che phủ bằng vải, ẩn chứa bí mật.",
    24: "Dấu cộng, nơi gặp nhau của hai đường.",
    25: "Dùng để xem bói, tiên đoán tương lai.",
    26: "Một đốt tre, nơi dâng tế lễ.",
    27: "Vách núi thẳng đứng, tạo thành hang động.",
    28: "Một góc nhỏ riêng tư, chỉ có một mình.",
    29: "Một bàn tay, ngón tay gợi ý thêm lần nữa.",
    30: "Một hình vuông, lỗ mở để ăn uống.",
    31: "Hộp kín, bao quanh hoàn toàn.",
    32: "Đất bề mặt, nơi trồng trọt xây dựng.",
    33: "Con người cao quý, nhân vật ưu tú.",
    34: "Chân đi chậm, như người già.",
    35: "Tương tự chân đi, nhưng khác cách.",
    36: "Mặt trời lặn, bóng tối buông xuống.",
    37: "Con người xõa tay, sự rộng lớn.",
    38: "Người phụ nữ quỳ, tượng trưng nữ giới.",
    39: "Em bé nhỏ, tượng trưng con cái.",
    40: "Mái nhà che chở, tạo căn nhà.",
    41: "Khoảng cách ngắn, đơn vị cơ bản.",
    42: "Một hạt nhỏ, biểu thị điều bé xíu.",
    43: "Người yếu ớt, mọi chuyện khó khăn.",
    44: "Xác chết nằm, biểu thị chết chóc.",
    45: "Mầm cây mọc lên, hy vọng sống mới.",
    46: "Ba đỉnh núi xếp chồng lên nhau.",
    47: "Dòng sông chảy, giữa hai bờ.",
    48: "Khung công trình, biểu thị lao động.",
    49: "Bản thân tôi, sự tự nhận thức.",
    50: "Chiếc khăn vuông, dùng để lau.",
    51: "Cái gậy hoặc thanh ngang.",
    52: "Rất nhỏ bé, như hạt bụi gió.",
    53: "Mái nhà rộng, che phủ tất cả.",
    54: "Bước dài sang một bên, tiến tới.",
    55: "Hai tay ghép lại, cảm ơn.",
    56: "Mũi tên bắn ra, tấn công mục.",
    57: "Cái cung bắn tên, sức mạnh.",
    58: "Đầu nhím với gai, phòng thủ.",
    59: "Ba sợi tóc, tượng trưng.",
    60: "Bước chân sang bên, đi bộ.",
    61: "Tim đập, trái tim cảm xúc.",
    62: "Chiến giáo, vũ khí cổ đại.",
    63: "Cửa căn nhà, cơ sở cuộc sống.",
    64: "Tay với năm ngón, công cụ lao động.",
    65: "Cành cây nhánh, phân tách.",
    66: "Đánh nhẹ bằng gậy, kiểm soát.",
    67: "Những nét chữ viết, văn hoá.",
    68: "Cái đo lường, giả tạ.",
    69: "Cái rìu cắt gỗ, công cụ.",
    70: "Hình vuông hoàn hảo.",
    71: "Không có gì, sự trống rỗng.",
    72: "Mặt trời sáng rực, nguồn sáng.",
    73: "Miệng mở nói, giao tiếp.",
    74: "Mặt trăng tròn, ánh sáng đêm.",
    75: "Cây cối mọc, sự sống xanh.",
    76: "Miệng há, biểu thị thiếu.",
    77: "Chân dừng lại, ngừng bước.",
    78: "Xác chết, biểu thị xấu xa.",
    79: "Chiếc gậy, vũ khí cơ bản.",
    80: "Không được phép, cấm chỉ.",
    81: "Hai người đứng cạnh.",
    82: "Sợi lông, biểu thị mềm.",
    83: "Họ của người, danh tính.",
    84: "Hơi thở, năng lượng sống.",
    85: "Nước chảy, sự dịu dàng.",
    86: "Lửa bùng cháy, nhiệt độ cao.",
    87: "Móng vuốt sắc bén.",
    88: "Cha của gia đình, bảo vệ.",
    89: "Đương kết hợp, hòa quyện.",
    90: "Mảnh gỗ bẻ ra.",
    91: "Miếng đứt, nửa cái gì.",
    92: "Hàng răng cười, giao tiếp.",
    93: "Con trâu mạnh, lao động.",
    94: "Con chó trung thành, bảo vệ.",
    95: "Màu đen huyền bí.",
    96: "Ngọc quý cổ, giá trị cao.",
    97: "Trái dưa tròn, cái gì ngon.",
    98: "Ngói mái nhà, che phủ.",
    99: "Ngọt lịm, hương vị dễ chịu.",
    100: "Sự sống mới, tự do.",
    101: "Dùng để làm gì, có ích.",
    102: "Ruộng lúa mênh mông.",
    103: "Tấm vải, đơn vị đo.",
    104: "Bệnh tật, khổ đau.",
    105: "Gạt ngược, lật lọng.",
    106: "Màu trắng sạch, sáng.",
    107: "Da người, vỏ ngoài.",
    108: "Bát ăn, vật dụng nhà bếp.",
    109: "Mắt nhìn, cửa sổ tâm hồn.",
    110: "Chiến giáo dài, tấn công.",
    111: "Mũi tên bay, chuẩn xác.",
    112: "Đá cứng, chắc chắn.",
    113: "Chỉ thị của thần linh.",
    114: "Dấu vết trên đất.",
    115: "Lúa vàng, sự sung túc.",
    116: "Hang động, chỗ ẩn trú.",
    117: "Đứng thẳng, thành lập.",
    118: "Tre thẳng mềm dẻo.",
    119: "Hạt gạo, lương thực.",
    120: "Sợi tơ tớ, kết nối.",
    121: "Cái chum sành, chứa nước.",
    122: "Cái lưới câu cá, bắt.",
    123: "Con dê, tính tình hiền.",
    124: "Lông vũ bay, nhẹ.",
    125: "Người già, sự yếu.",
    126: "Cái tóc dài, liên kết.",
    127: "Cái cày, canh tác.",
    128: "Tai nghe, lắng nghe.",
    129: "Cây bút viết, sáng tạo.",
    130: "Thịt người, cơ thể.",
    131: "Bề tôi quỳ, tôn kính.",
    132: "Bản thân tôi, tự giác.",
    133: "Đến đích, hoàn thành.",
    134: "Cối giã gạo, chế biến.",
    135: "Lưỡi nói, giao tiếp.",
    136: "Sai lệch, trái chiều.",
    137: "Thuyền trên sông, khám phá.",
    138: "Dừng lại, cứng rắn.",
    139: "Màu sắc đa dạng.",
    140: "Cỏ xanh, tự nhiên.",
    141: "Hổ hung dữ, sức mạnh.",
    142: "Sâu bọ, sinh vật nhỏ.",
    143: "Máu chảy, sự sống.",
    144: "Đi bộ, hành động.",
    145: "Áo quần, che thân.",
    146: "Che phủ phía tây.",
    147: "Mắt nhìn, hiểu biết.",
    148: "Sừng con động vật.",
    149: "Miệng nói lời, giao tiếp.",
    150: "Khe núi sâu, tiếng vang.",
    151: "Hạt đậu, dinh dưỡng.",
    152: "Con heo, tính khí.",
    153: "Thú hoang, bản năng.",
    154: "Vỏ sò cổ, tiền tệ.",
    155: "Màu đỏ rực, cháy bỏng.",
    156: "Chạy nhanh, trốn chạy.",
    157: "Chân bước, hành động.",
    158: "Cơ thể con người.",
    159: "Xe chạy, giao thông.",
    160: "Cay khổ, khó nhọc.",
    161: "Thời gian sáng tỏ.",
    162: "Đi xa, di chuyển.",
    163: "Vùng đất, thành phố nhỏ.",
    164: "Rượu ngon, lễ hội.",
    165: "Phân biệt sáng tối.",
    166: "Làng quê, khoảng cách.",
    167: "Kim loại quý, giá.",
    168: "Dài sâu, lâu dài.",
    169: "Cửa hai cánh, ra vào.",
    170: "Gò đất cao, địa hình.",
    171: "Theo kịp, dần dần.",
    172: "Chim bay, nhẹ nhàng.",
    173: "Mưa tuôn, sự tươi mát.",
    174: "Xanh lam, màu sắc.",
    175: "Không phải, phủ định.",
    176: "Mặt người, bề mặt.",
    177: "Da thú, thay đổi.",
    178: "Da đã xử lý.",
    179: "Rau hẹ mùi, ăn.",
    180: "Âm thanh vang.",
    181: "Đầu người, trang sách.",
    182: "Gió thổi, sự bay bổng.",
    183: "Bay cao, tự do.",
    184: "Ăn cơm, dinh dưỡng.",
    185: "Đầu tiên, lãnh đạo.",
    186: "Mùi thơm, quyến rũ.",
    187: "Con ngựa, tốc độ.",
    188: "Xương chắc, cơ bản.",
    189: "Cao vút, tầm nhìn rộng.",
    190: "Tóc dài, nhan sắc.",
    191: "Chiến đấu, cạnh tranh.",
    192: "Rượu lễ, tôn kính.",
    193: "Cái đỉnh cổ, nấu.",
    194: "Con quỷ, bí ẩn.",
    195: "Con cá, sự bơi lội.",
    196: "Con chim, bay lượn.",
    197: "Đất mặn, khô cằn.",
    198: "Con hươu, tài lộc.",
    199: "Lúa mạch vàng.",
    200: "Cây gai, sợi vải.",
    201: "Vàng rực, giá trị.",
    202: "Lúa nếp, bánh.",
    203: "Đen kịt, tối tăm.",
    204: "May vá áo, công phu.",
    205: "Ếch eo ơi, nhảy nhót.",
    206: "Cái đỉnh ba chân.",
    207: "Cái trống, phô trương.",
    208: "Con chuột, tinh tế.",
    209: "Cái mũi sắc, ngửi.",
    210: "Ngang bằng, cân xứng.",
    211: "Hàng răng, cắn nhai.",
    212: "Con rồng huyền bí.",
    213: "Con rùa lâu đời.",
    214: "Ống sáo, tiếng gọi."
}

# Đọc file HTML
with open('e:\\profineCV\\Web_learn_Chinese_pro\\public\\user\\radicals-214.html', 'r', encoding='utf-8') as f:
    content = f.read()

# Thêm mnemonic vào mỗi dòng radical
for num, mnemonic in mnemonics.items():
    # Tìm pattern của dòng radical hiện tại
    pattern = rf'({{ number: {num},.*?examples: \[.*?\])(?: }},?)'
    
    # Kiểm tra xem dòng có chứa mnemonic chưa
    if f'mnemonic:' not in content:
        replacement = rf'\1, mnemonic: "{mnemonic.replace('"', '\\"')}"' + r'}'
        content = re.sub(pattern, replacement, content, count=1)

# Ghi lại file
with open('e:\\profineCV\\Web_learn_Chinese_pro\\public\\user\\radicals-214.html', 'w', encoding='utf-8') as f:
    f.write(content)

print("Mnemonics added successfully!")
